default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

services:
  - docker:dind

before_script:
  - amazon-linux-extras install docker
  - yum -y install make 
  - aws --version
  - docker --version

variables:
  DEV_ENV: nlp-dev-base
  DOCKER_HOST: tcp://docker:2375

stages:
  - build-deploy

build-and-deploy-job:
  stage: build-deploy
  script:
    - cd $DEV_ENV
    - export KEY_ID=$AWS_ACCESS_KEY_ID # export variables and pass to make file  
    - export KEY_VALUE=$AWS_SECRET_ACCESS_KEY # makefile passes variables to  dockerfile using --build-args, variables are first declared in dockerfile
    - export TEST_VAR=$TEST_VAR
    - make ecr_login
    - make ecr_build
    - make ecr_push
  