default:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

before_script:
  - apt install make

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - export KEY_ID=$AWS_ACCESS_KEY_ID
    - export KEY_VALUE=$AWS_SECRET_ACCESS_KEY
    - make ecr_login
    - make ecr_build
  
deploy-job:
  stage: deploy
  script:
    - make ecr_push
  