default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

services:
  - docker:dind

before_script:
  - amazon-linux-extras install docker make
  - aws --version
  - docker --version

variables:
  DEV_ENV: nlp-dev-base
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - cd $DEV_ENV
    - export KEY_ID=$AWS_ACCESS_KEY_ID
    - export KEY_VALUE=$AWS_SECRET_ACCESS_KEY
    - make ecr_login
    - make ecr_build
  
deploy-job:
  stage: deploy
  script:
    - cd $DEV_ENV
    - make ecr_push
  